name: pre-commit

# MANUAL_TRIGGER
# on:
#   push:
#     branches:
#       - master
#       - develop
#     tags:
#       - '*'
#   pull_request:
#     paths:
#       - .github/workflows/pre-commit-hooks-test.yml
#       - .pre-commit-hooks.yaml
#       - tests/pre-commit-hooks/*
#       - requirements.txt
#       - setup.py
on: [repository_dispatch, workflow_dispatch]

jobs:
  hooks-test:
    runs-on: ubuntu-latest
    name: test hooks
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
      - name: Test hooks
        run: |
          ./tests/pre-commit-hooks/test.sh

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
